"""Extract official Lua signatures for every REAPER API used in our scripts.

Run: python tools/audit_api.py runtime/reascripthelp.html
Input is the official REAPER reference downloaded by the developer, not a mock.
"""
import html
from pathlib import Path
import re
import sys

reference = html.unescape(re.sub('<[^>]+>', '', Path(sys.argv[1]).read_text(encoding='utf8')))
used = set()
for path in Path('reaper').rglob('*.lua'):
    if path.name == 'dkjson.lua':
        continue
    used.update(re.findall(r'\b(?:reaper|R)\.([A-Za-z0-9_]+)\s*\(', path.read_text(encoding='utf8')))
lines = []
missing = []
for name in sorted(used):
    matches = [line for line in reference.splitlines() if line.startswith('Lua:') and re.search(r'\breaper\.'+name+r'\(', line)]
    if matches:
        lines.append(matches[0])
    else:
        missing.append(name)
Path('docs/api-signatures.txt').write_text('Official reference: https://www.reaper.fm/sdk/reascript/reascripthelp.html\nGenerated by REAPER 7.79; retrieved 2026-09-07.\n\n'+'\n'.join(lines)+'\n\nBuilt-ins / inspect separately: '+(', '.join(missing) or 'none')+'\n',encoding='utf8')
print(f'{len(lines)} official signatures; built-ins/manual review: {missing}')
